"""add bio to user

Revision ID: 493af444c2d3
Revises: 806ab11fa1eb
Create Date: 2026-05-17 17:30:17.024531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493af444c2d3'
down_revision = '806ab11fa1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
